# Generated by Django 5.0.6 on 2024-07-01 08:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_entry", "0002_alter_student_roll_no"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_name", models.CharField(max_length=128)),
                ("country", models.CharField(max_length=128)),
            ],
        ),
    ]
