# Generated by Django 5.0.6 on 2024-07-02 04:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_entry", "0003_customer"),
    ]

    operations = [
        migrations.CreateModel(
            name="Empolyee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("employee_id", models.IntegerField()),
                ("employee_name", models.CharField(max_length=128)),
                ("desgination", models.CharField(max_length=128)),
                ("salary", models.DecimalField(decimal_places=2, max_digits=10)),
                ("retirement", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "other_benefits",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "total_benefits",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "total_compenstation",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
            ],
        ),
    ]
